const dotenv = require('dotenv');
dotenv.config();

module.exports = {
    data1C_host: process.env.DATA1C_HOST || '',
    data1C_auth: process.env.DATA1C_AUTH || '',

    allowedCorsOrigins: [''],

    skipWords: ['дай', 'будь', 'будьласка', 'ласка', 'нехай', 'тисячі', 'три'],

    allowedTextCommands: [
        '/start',
        '/search',
        '🔊 Надіслати аудіо',
        '📝 Надіслати текст',
        '📦 Прорахувати вантаж',
        'ℹ️ Допомога',
        '🏙️ Список міст',
        '🚢 Список портів',
    ],

    ports: [
        { text: 'Агмедабад', value: 'AHMEDABAD', code: 'INAMD' },
        { text: 'Александрія', value: 'ALEXANDRIA', code: 'EGALY' },
        { text: 'Альтаміра', value: 'ALTAMIRA (MEXICO)', code: 'MXATM' },
        { text: 'Атланта', value: 'ATLANTA', code: 'USATL' },
        { text: 'Асунсьйон', value: 'ASUNCION', code: 'PYASU' },
        { text: 'Ашдод', value: 'ASHDOD', code: 'ILASH' },
        { text: 'Балтимор', value: 'BALTIMORE', code: 'USBAL' },
        { text: 'Бангалор', value: 'BANGALORE', code: 'INBLR' },
        { text: 'Бангкок', value: 'BANGKOK', code: 'THBKK' },
        { text: 'Барода', value: 'BARODA', code: 'INBRC' },
        { text: 'Бейрут', value: 'BEIRUT', code: 'LBBEY' },
        { text: 'Богота', value: 'BOGOTA', code: 'COBOG' },
        { text: 'Бостон', value: 'BOSTON', code: 'USBOS' },
        { text: 'Брісбен', value: 'BRISBANE', code: 'AUBNE' },
        { text: 'Букараманга', value: 'BUCARAMANGA', code: 'COBGA' },
        { text: 'Буенос-Айрес', value: 'BUENOS AIRES', code: 'ARBUE' },
        { text: 'Ванкувер', value: 'VANCOUVER', code: 'CAVAN' },
        { text: 'Варшава', value: 'WARSZAWA', code: 'PLWAW' },
        { text: 'Веракрус', value: 'VERACRUZ', code: 'MXVER' },
        { text: 'Гваякіль', value: 'GUAYAQUIL', code: 'ECGYE' },
        { text: 'Гдиня', value: 'GDYNIA', code: 'PLGDY' },
        { text: 'Гонконг', value: 'HONG KONG', code: 'HKHKG' },
        { text: 'Гуанчжоу', value: 'GUANGZHOU', code: 'CNCAN' },
        { text: 'Да-Нанг', value: 'DA NANG', code: 'VNDAD' },
        { text: 'Далянь', value: 'DALIAN', code: 'CNDLC' },
        { text: 'Даллас', value: 'DALLAS', code: 'USDAL' },
        { text: 'Детройт', value: 'DETROIT', code: 'USDTT' },
        { text: 'Джайпур', value: 'JAIPUR', code: 'INJAI' },
        { text: 'Джакарта', value: 'JAKARTA', code: 'IDJKT' },
        { text: 'Джидда', value: 'JEDDAH', code: 'SAJED' },
        { text: 'Донгуань', value: 'DONGGUAN', code: 'GUADN' },
        { text: 'Дубай', value: 'DUBAI', code: 'AEDXB' },
        { text: 'Дурбан', value: 'DURBAN', code: 'ZADUR' },
        { text: 'Йоганнесбург', value: 'JOHANNESBURG', code: 'ZAJNB' },
        { text: 'Йокогама', value: 'YOKOHAMA', code: 'JPYOK' },
        { text: 'Інчхон', value: 'INCHEON', code: 'KRINC' },
        { text: 'Індіанаполіс', value: 'INDIANAPOLIS', code: 'USIND' },
        { text: 'Ітажаї', value: 'ITAJAI', code: 'BRITJ' },
        { text: 'Каліяо', value: 'CALLAO', code: 'PECLL' },
        { text: 'Калі', value: 'CALI', code: 'COCLO' },
        { text: 'Калькутта', value: 'CALCUTTA', code: 'INCCU' },
        { text: 'Каноас', value: 'CANOAS', code: 'BRQNS' },
        { text: 'Каошіунг', value: 'KAOHSIUNG', code: 'TWKHH' },
        { text: 'Карачі', value: 'KARACHI', code: 'PKKHI' },
        { text: 'Картахена', value: 'CARTAGENA', code: 'COCTG' },
        { text: 'Касабланка', value: 'CASABLANCA', code: 'MACAS' },
        { text: 'Кейптаун', value: 'CAPE TOWN', code: 'ZACPT' },
        { text: 'Кілунг', value: 'KEELUNG', code: 'TWKEL' },
        { text: 'Клівленд', value: 'CLEVELAND', code: 'USCLE' },
        { text: 'Кобе', value: 'KOBE', code: 'JPUKB' },
        { text: 'Кочабамба', value: 'COCHABAMBA', code: 'BOCBB' },
        { text: 'Колон', value: 'COLON', code: 'PAONX' },
        { text: 'Коломбо', value: 'COLOMBO', code: 'LKCMB' },
        { text: 'Кордова', value: 'CORDOBA', code: 'ARCOR' },
        { text: 'Куритіба', value: 'CURITIBA', code: 'BRCWB' },
        { text: 'Кувейт', value: 'KUWAIT', code: 'KWKWI' },
        { text: 'Ла-Пас', value: 'LA PAZ', code: 'MXLAP' },
        { text: 'Лос-Анджелес', value: 'LOS ANGELES', code: 'USLAX' },
        { text: 'Лоян', value: 'LUOYANG', code: 'CNLYA' },
        { text: 'Лудхіана', value: 'LUDHIANA', code: 'INLUH' },
        { text: 'Маніла', value: 'MANILA', code: 'PHMNL' },
        { text: 'Маямі', value: 'MIAMI', code: 'USMIA' },
        { text: 'Медельїн', value: 'MEDELLIN', code: 'COMDE' },
        { text: 'Мельбурн', value: 'MELBOURNE', code: 'AUMEL' },
        { text: 'Мендоса', value: 'MENDOZA', code: 'ARMDZ' },
        { text: 'Модзі', value: 'MOJI', code: 'JPMOJ' },
        { text: 'Монреаль', value: 'MONTREAL', code: 'CAMTR' },
        { text: 'Монтевідео', value: 'MONTEVIDEO', code: 'UYMVD' },
        { text: 'Мумбаї', value: 'MUMBAI', code: 'INBOM' },
        { text: 'Нагоя', value: 'NAGOYA', code: 'JPNGY' },
        { text: 'Нагпур', value: 'NAGPUR', code: 'INNAG' },
        { text: 'Нхава-Шева', value: 'NHAVA SHEVA', code: 'INNAV' },
        { text: 'Нью-Делі', value: 'NEW DELHI', code: 'INNDL' },
        { text: 'Нью-Йорк', value: 'NEW YORK', code: 'USNYK' },
        { text: 'Нінбо', value: 'NINGBO', code: 'CNNGB' },
        { text: 'Окленд', value: 'AUCKLAND', code: 'NZAKL' },
        { text: 'Окленд', value: 'OAKLAND', code: 'USOKL' },
        { text: 'Осака', value: 'OSAKA', code: 'JPSOA' },
        { text: 'Пасір-Гуданг', value: 'PASIR GUDANG', code: 'MYPGU' },
        { text: 'Пекін', value: 'BEIJING', code: 'CNBJS' },
        { text: 'Пенанг', value: 'PENANG', code: 'MYPEN' },
        { text: 'Порт-Кланг', value: 'PORT KLANG', code: 'MYPKG' },
        { text: 'Пуна', value: 'PUNE', code: 'INPNQ' },
        { text: 'Пусан', value: 'BUSAN', code: 'KRPUS' },
        { text: 'Ріо-де-Жанейро', value: 'RIO DE JANEIRO', code: 'BRRIO' },
        { text: 'Росаріо', value: 'ROSARIO', code: 'ARROS' },
        { text: 'Сан-Антоніо', value: 'SAN ANTONIO', code: 'CLSAI' },
        { text: 'Сан-Хосе', value: 'SAN JOSE', code: 'CRSJO' },
        { text: 'Санта-Крус', value: 'SANTA CRUZ', code: 'BOSRZ' },
        { text: 'Сантус', value: 'SANTOS', code: 'BRSSZ' },
        { text: 'Себу', value: 'CEBU', code: 'PHCEB' },
        { text: 'Семаранг', value: 'SEMARANG', code: 'IDSRG' },
        { text: 'Сінган (Тяньцзінь)', value: 'XINGANG - TIANJIN', code: 'CNTXG' },
        { text: 'Сінгапур', value: 'SINGAPORE', code: 'SGSIN' },
        { text: 'Сіань', value: "XI'AN", code: 'CNXIA' },
        { text: 'Стамбул', value: 'ISTANBUL', code: 'TRIST' },
        { text: 'Сурабая', value: 'SURABAYA', code: 'IDSUB' },
        { text: 'Сідней', value: 'SYDNEY', code: 'AUSYD' },
        { text: 'Сямень', value: 'XIAMEN', code: 'CNXMN' },
        { text: 'Тайвань', value: 'TAIYUAN', code: 'CNTYN' },
        { text: 'Тайчжун', value: 'TAICHUNG', code: 'TWTXG' },
        { text: 'Тіяньцзінь', value: 'Tianjin', code: 'CNTSN' },
        { text: 'Токіо', value: 'TOKYO', code: 'JPTYO' },
        { text: 'Торонто', value: 'TORONTO', code: 'CATOR' },
        { text: 'Тутикорін', value: 'TUTICORIN', code: 'INTUT' },
        { text: 'Філадельфія', value: 'PHILADELPHIA', code: 'USPHL' },
        { text: 'Фошань', value: 'FOSHAN', code: 'CNFOS' },
        { text: 'Фуцін', value: 'Fuqing', code: 'CNFUG' },
        { text: 'Фучжоу', value: 'FUZHOU', code: 'CNFOC' },
        { text: 'Хайдарабад', value: 'HYDERABAD', code: 'INHYD' },
        { text: 'Хайфа', value: 'HAIFA', code: 'ILHFA' },
        { text: 'Хайфон', value: 'HAIPHONG', code: 'VNHPH' },
        { text: 'Хаката/Фукуока', value: 'HAKATA/FUKUOKA', code: 'JPHKT' },
        { text: 'Хошимін (Кат Лай)', value: 'HO CHI MINH CAT LAI', code: 'VNSGN' },
        { text: 'Х`юстон', value: 'HOUSTON', code: 'USHOU' },
        { text: 'Ченду', value: 'CHENGDU', code: 'CNCTU' },
        { text: 'Ченнай', value: 'CHENNAI', code: 'INMAA' },
        { text: 'Чжуншань', value: 'ZHONGSHAN', code: 'CNZSN' },
        { text: 'Чжухай', value: 'ZHUHAI', code: 'CNZUH' },
        { text: 'Чженчжоу', value: 'ZHENGZHOU', code: 'CNCGO' },
        { text: 'Чикаго', value: 'CHICAGO', code: 'USCHI' },
        { text: 'Чіттаґонґ', value: 'CHATTOGRAM', code: 'BDCGP' },
        { text: 'Чарлстон', value: 'CHARLESTON', code: 'USCST' },
        { text: 'Шаньтоу', value: 'SHANTOU', code: 'CNSWA' },
        { text: 'Шанхай', value: 'SHANGHAI', code: 'CNSHA' },
        { text: 'Шарлотт', value: 'CHARLOTTE', code: 'USCLT' },
        { text: 'Шеньчжень', value: 'SHENZHEN', code: 'CNSZX' },
        { text: 'Шимідзу', value: 'SHIMIZU', code: 'JPSMZ' },
        { text: 'Шицзячжуан', value: 'SHIJIAZHUANG', code: 'CNSJW' },
        { text: 'Шунде', value: 'SHUNDE', code: 'CNSUD' },
        { text: 'Циндао', value: 'QINGDAO', code: 'CNTAO' },
        { text: 'Цзянмень', value: 'JIANGMEN', code: 'CNJMN' },
        { text: 'Ухань', value: 'WUHAN', code: 'CNWUH' },
    ],

    cities: [
        { text: 'Бердичів', value: 'BERDYCHIV' },
        { text: 'Біла Церква', value: 'BILA CERKVA' },
        { text: 'Бориспіль', value: 'BORYSPIL' },
        { text: 'Боярка', value: 'BOYARKA' },
        { text: 'Бровари', value: 'BROVARY' },
        { text: 'Вільногірськ', value: 'VOLNOGORSK' },
        { text: 'Вінниця', value: 'VINNYCJA' },
        { text: 'Дніпро', value: 'DNIPRO' },
        { text: 'Дрогобич', value: 'DROHOBYCH' },
        { text: 'Енергодар', value: 'ENERHODAR' },
        { text: 'Житомир', value: 'ZHYTOMYR' },
        { text: 'Запоріжжя', value: 'ZAPORIZHIA' },
        { text: 'Звягель', value: 'NOVOGRAD-VOLYNSKIJ' },
        { text: 'Івано-Франківськ', value: 'IVANO FRANKIVSK' },
        { text: 'Ізмаїл', value: 'ISMAIL' },
        { text: 'Калуш', value: 'KALUSH' },
        { text: 'Київ', value: 'KYIV' },
        { text: 'Ковель', value: 'KOVEL' },
        { text: 'Конотоп', value: 'KONOTOP' },
        { text: 'Краматорськ', value: 'KRAMATORSK' },
        { text: 'Кременчук', value: 'KREMENCHUG' },
        { text: 'Кривий Ріг', value: 'KRIVIY RIH' },
        { text: 'Кропивницький', value: 'KROPIVNITSKY' },
        { text: 'Луцьк', value: 'LUTSK' },
        { text: 'Львів', value: 'LVIV' },
        { text: 'Маріуполь', value: 'MARIUPOL' },
        { text: 'Мелітополь', value: 'MELITOPOL' },
        { text: 'Миколаїв', value: 'NIKOLAEV' },
        { text: 'Мукачеве', value: 'MUKACHEVE' },
        { text: 'Нікополь', value: 'NIKOPOL' },
        { text: 'Новомосковськ', value: 'NOVOMOSKOVSK' },
        { text: 'Новояворівськ', value: 'NOVOIAVORIVSK' },
        { text: 'Обухів', value: 'OBUKHIV' },
        { text: 'Одеса', value: 'ODESSA' },
        { text: 'Полтава', value: 'POLTAVA' },
        { text: 'Рівне', value: 'RIVNE' },
        { text: 'Сміла', value: 'SMILA' },
        { text: 'Стрий', value: 'STRYJ' },
        { text: 'Суми', value: 'SUMY' },
        { text: 'Тернопіль', value: 'TERNOPIL' },
        { text: 'Тячів', value: 'TIACHIV' },
        { text: 'Ужгород', value: 'UZHGOROD' },
        { text: 'Харків', value: 'KHARKIV' },
        { text: 'Херсон', value: 'KHERSON' },
        { text: 'Хмельницький', value: 'KHMELNITSKY' },
        { text: 'Червоноград', value: 'CHERVONOGRAD' },
        { text: 'Черкаси', value: 'CHERKASY' },
        { text: 'Чернівці', value: 'CHERNIVTSI' },
        { text: 'Чернігів', value: 'CHERNIHIV' },
        { text: 'Чорноморськ', value: 'CHORNOMORKS' },
        { text: 'Чорноморськ', value: 'CHORNOMORSK' },
        { text: 'Шостка', value: 'SHOSTKA' }
    ],


    data1c_info: `• Tariffs for goods with one cargo space more than 2000 kg or dimensions (length, width, height) more than 2.0 m - must be checked separately
• Tariff for general, safe, stacked cargo.
• Cashless payment only
• Truck rates can be change from ETA date
• Pick up by customer truck 15USD/bl
• 5 days free of charges. Storage start from 6th day - EUR 3,5 x w/m x day - min. EUR 20 from 3rd week EUR 5 x w/m x day
•for EXW rates may occurred additional charges
•Separate truck 48hours free. Groupage truck 24hours free. Then 100USD/day till 3 days and 150USD/day from 3days
•Rates for palletized cargo
•Rates for 1 bl, 1 shipper and 1 cnee
•Please note all our offers are subject to PSS or GRI without prior notice
•We bill in UAH+3%  by NBU rate on date of invoice
•For 1 export license within 5 items，if more than 5 items，plus additional charges
•We do not provide export documents in case of purchase through our agent
•For IMO STORAGE:
•3days free, from 4day EUR 6EUR x w/m x day-min 70EUR
•We are not responsible for the package(cargo)  integrity if the above conditions are not met.
•In case of cancellation booking after cut of  - dead freight  will be apply for LCL / LTL 
•Loading fee 5 usd per w/m will be apply in case self pick up 
•Please ALWAYS pay attention to the validity of the offer before ETD, as the tariff may change according to the validity of the offer
•The customs broker handles clearance and may decline if HS code/documents are unsuitable. Storage fees may apply.`
}